project_id = "yrfjskwikknbzganhdjp"

[functions.analyze-text]
verify_jwt = false

[functions.generate-fill-blanks]
verify_jwt = false

[functions.generate-multiple-choice]
verify_jwt = false

[functions.generate-short-answer]
verify_jwt = false

[functions.solve-problems]
verify_jwt = false

[functions.analyze-weaknesses]
verify_jwt = false

[functions.generate-recommended-problems]
verify_jwt = false